// Code generated by goctl. DO NOT EDIT.
package types

type TestResp struct {
	Date string `json:"data"`
	Name string `json:"name"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token   string `json:"token"`
	Expires int64  `json:"expires"`
}

type RegisterRequest struct {
	Mobile   string `json:"mobile"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Status bool `json:"status"`
}

type UserInfoResp struct {
	Id          int    `json:"id"`
	Name        string `json:"name"`
	Mobile      string `json:"mobile"`
	Avatar      string `json:"avatar"`
	CreatedTime string `json:"createdTime"`
}

type UrlRequest struct {
	Uri string `json:"uri"`
}

type UrlResp struct {
	Uri string `json:"uri"`
}
