// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UserInfoRequest struct {
	Id int `path:"id"`
}

type UserInfoResp struct {
	Id          int    `json:"id"`
	Name        int    `json:"name"`
	Mobile      string `json:"mobile"`
	Avatar      string `json:"avatar"`
	CreatedTime string `json:"createdTime"`
}
