// Code generated by goctl. DO NOT EDIT.
package types

type TestResp struct {
	Date string `json:"data"`
	Name string `json:"name"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	Mobile   string `json:"mobile"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Status bool `json:"status"`
}

type UserInfoResp struct {
	Id          int    `json:"id"`
	Name        int    `json:"name"`
	Mobile      string `json:"mobile"`
	Avatar      string `json:"avatar"`
	CreatedTime string `json:"createdTime"`
}
