// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "go-zero-short/internal/handler/auth"
	testing "go-zero-short/internal/handler/testing"
	user "go-zero-short/internal/handler/user"
	"go-zero-short/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/testing",
				Handler: testing.TestingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.AuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info/:id",
				Handler: user.UserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
